//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtityFrameworkLinq_esempio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medal
    {
        public long Id_Athlete { get; set; }
        public int Id_Game { get; set; }
        public int Id_Event { get; set; }
        public string Medal1 { get; set; }
    
        public virtual AthletesNf AthletesNf { get; set; }
        public virtual Event Event { get; set; }
        public virtual Game Game { get; set; }
    }
}
